services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photogram
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    restart: always
    ports:
      - "1081:1080"
      - "1026:1025"
  ###< symfony/mailer ###

  ###> dev-tools ###
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
  ###< dev-tools ###

volumes:
  database_data:
